### ISSUE TITLE
Selecting minute outside timeStep will leave dropdown unselected

### ISSUE THREAD

**Issue by fullflavedave** [dubert/react-kronos#70]
If the timeStep is set to 15 minutes, and you enter "10:32 PM", the next time you click on the time field, the dropdown will be unselected, starting at 12:00 AM, and the user will need to scroll way down to select another time close to 10:32 PM.  This is a usability issue for our users.

**Comment by felixakiragreen** [comment]
I'll test this out today and if everything looks good, merge it and push a new release.

Thanks for the PR!

**Comment by felixakiragreen** [comment]
@fullflavedave I understand the issue now. Correct me if I'm wrong, but this is only an issue for when `timeStep` is set? When `timeStep` is not set and the user enters "10:32 PM" then it does scroll to the correct place.

I reviewed your PR, and instead of adding a new property, I would like to make the scrolling to the correct spot always the default behavior. Would this address your use-case? The value the user entered ("10:32 PM") would not be selected, however, the user would not need to scroll to select another time close to it.

**Comment by fullflavedave** [comment]
Thanks for taking a look!  Yes -- this is only an issues with timeStep set.  The above plan you stated of always scrolling to the correct spot would take care of my use-case.

**Comment by felixakiragreen** [comment]
Fixed in 1.7.1.
